---
- name: create s3 bucket
#  aws_s3:
#    bucket: "{{ fakes3_bucket_name }}"
#    mode: create
#    s3_url: http://localhost:4567
#  s3:
#    bucket: "{{ fakes3_bucket_name }}"
#    mode: create
#    s3_url: "http://localhost:4567"
  s3_bucket:
    name: "{{ fakes3_bucket_name }}"
    s3_url: fakes3://localhost:4567
  when: fakes3_create_bucket
